"""Allow email to be null

Revision ID: 017efc0f6b50
Revises: 3f2bda90431a
Create Date: 2025-02-25 15:33:23.989860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017efc0f6b50'
down_revision = '3f2bda90431a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
